#!/usr/bin/env bash

. "$ERLVM_ROOT/scripts/load_functions" || return 1

erlvm() {
	if [[ "$ERLVM_ROOT" == "" ]]; then
		erlvm_error "ERLVM_ROOT not set. Please source \$ERLVM_ROOT/scripts/erlvm"
		return 1
	fi

	if [[ -d $ERLVM_ROOT/.git ]]; then
		mv "$ERLVM_ROOT/.git" "$ERLVM_ROOT/git.bak"
		if [[ $? -ne 0 ]]; then
			erlvm_error "Failed to move git info out of the way"
			return 1
		fi
	fi

	if [[ ! -d $ERLVM_ROOT ]]; then
		erlvm_error "ERLVM_ROOT does not exist, please reinstall erlvm!"
		return 1
	fi

	[[ ! -d $ERLVM_ROOT/logs ]] && mkdir -p "$ERLVM_ROOT/logs" > /dev/null 2>&1

	$ERLVM_ROOT/bin/erlvm $@
}
