#!/usr/bin/env bash

LS_ERROR="ERLVM couldn't find ls"
SED_ERROR="ERLVM couldn't find sed"
GREP_ERROR="ERLVM couldn't find grep"
SORT_ERROR="ERLVM couldn't find sort"
HEAD_ERROR="ERLVM couldn't find head"

LS_PATH=$(unalias ls &> /dev/null; command -v ls) || erlvm_warn "$LS_ERROR" || return 1
SED_PATH=$(unalias sed &> /dev/null; command -v sed) || erlvm_warn "$SED_ERROR" || return 1
GREP_PATH=$(unalias grep &> /dev/null; command -v grep) || erlvm_warn "$GREP_ERROR" || return 1
SORT_PATH=$(unalias sort &> /dev/null; command -v sort) || erlvm_warn "$SORT_ERROR" || return 1
HEAD_PATH=$(unalias head &> /dev/null; command -v head) || erlvm_warn "$HEAD_ERROR" || return 1
